### ISSUE TITLE
Error: ENOENT: no such file or directory, open '...default.config.noon'

### ISSUE THREAD

**Issue by mspanish** [drawnepicenter/leximaven#23]
Trying to run `leximaven config init` on Windows - NODE_PATH is all a-ok, ,but I get this.

If I try to run leximaven I also get that this file is missing.

**Comment by drawnepicenter** [comment]
Windows support is incomplete, you may have to experiment with a version manager for Node like Nodist. The other option is to clone the repo and install it from that, then set up a command alias to point to the program binary in the bin folder. That's the fallback when NODE_PATH doesn't work. Please try these workarounds and let me know how it goes! :smile:

**Comment by mspanish** [comment]
Hello thanks very much, I've done a couple of workarounds and will let you know as soon as I test them - most likely tomorrow.

**Comment by drawnepicenter** [comment]
Can't support Windows right now.
